server {
    listen 80;
    server_name _;


    root /usr/share/nginx/html;
    index index.html;

    location /account/ {
        proxy_pass http://forum.backend.local:8080/account/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_read_timeout 60s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;

}